# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
submitit_folder: ${hydra.sweep.dir}
name: ${hydra.job.name}
cpus_per_task: 24
timeout_min: 60
