defaults:
  - encoder: resnet18
  - decoder: null
  - loss: cross_entropy
  - optimizer: adam
  - learning_rate_scheduler: null
  - logging: classification  # overwrites hydra.run.dir

_target_: model.classification.ClassificationModel
_recursive_: False
freeze_encoder: False
compile: False