# conda env create -f environment.yml
name: t2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchinfo
  - torchaudio
  - torchvision
  - lightning
  - hydra-core
  - hydra-submitit-launcher
  - matplotlib
  - pandas
  - pyarrow
  - wandb
  - timm
  - scipy
  - webdataset
  - rich
  - hydra-submitit-launcher

# conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
# conda install -c conda-forge torchinfo lightning hydra-core pandas wandb timm scipy webdataset
