# conda env create -f environment.yaml
name: dali
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchinfo
  - torchaudio
  - torchvision
  - lightning
  - hydra-core
  - hydra-submitit-launcher
  - matplotlib
  - pandas
#  - pyarrow
  - wandb
  - timm
  - scipy
  - webdataset
  - rich
# nvidia dali
  - pip
  - pip:
    - nvidia-dali-cuda120
