defaults:
  - learning_rate_monitor
  - model_checkpoint
  - rich_progress_bar
  - _self_

model_checkpoint:
  # dirpath: ${paths.output_dir}/checkpoints
  # filename: "epoch_{epoch:03d}"
  # monitor: "val/acc"
  # mode: "max"
  save_last: True
  # auto_insert_metric_name: False
