model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/ckpt
  # filename: "epoch_{epoch:03d}"
  # monitor: "val/acc"
  # mode: "max"
  save_last: True
  # auto_insert_metric_name: False
