name: sgd_no_schedule_sweep
description: "Exhaustive MNIST Softmax Regression Sweep"
method: bayes

metric:
  goal: maximize
  name: validation/acc

parameters:
  dataset.batch_size:
    values: [128, 256, 512, 1024, 2048]

  model.optimizer.lr:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.5
  model.optimizer.momentum:
    distribution: uniform
    min: 0.0
    max: 0.99
  # model.optimizer.weight_decay:
  #   min: 0.0
  #   max: 0.1

  # model.loss.label_smoothing:
  #   min: 0.0
  #   max: 0.1

  trainer.max_steps:
    distribution: normal
    mu:  3_000
    sigma: 300

run_cap: 1_000
# early_terminate:
#   min_iter: 1000


program: train.py
command:
- ${env}
- ${interpreter}
- ${program}
- trainer=cpu
- model/optimizer=sgd
- experiment=mnist/baseline
- ${args_no_hyphens}