name: sgd_no_schedule_sweep
description: "Exhaustive MNIST Softmax Regression Sweep"
method: bayes

metric:
  goal: maximize
  name: validation/acc

parameters:
  dataset.batch_size:
    values: [16, 32, 64, 128, 256, 512, 1024]

  model.optimizer.lr:
    min: 0.0001
    max: 0.5
  model.optimizer.momentum:
    min: 0.1
    max: 0.99
  model.optimizer.weight_decay:
    min: 0.0
    max: 0.1

  model.loss.label_smoothing:
    min: 0.0
    max: 0.1

  trainer.max_steps:
    min: 1_000
    max: 100_000

run_cap: 10 # _000
program: train.py
command:
- ${env}
- ${interpreter}
- ${program}
- trainer=cpu
- model/optimizer=sgd
- ${args_no_hyphens}