# @package _global_

# specify default configuration
# order of defaults determines which configs override each other
defaults:
  - hydra: default
  
  - dataset: mnist
  - model: classification
  - trainer: default

  - callbacks: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  - _self_
#   # config for hyperparameter optimization
#   - hparams_search: null

  - override hydra/launcher: ants

wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: mnist
  name: submitit
  job_type: devel
