name: cifar10
_target_: dataset.modules.cifar.CifarDataModule
root: ~/data/cifar10


batch_size: 64
num_workers: 8
mean: [0.5, 0.5, 0.5]
std:  [0.5, 0.5, 0.5]

classes: [
  airplane, automobile, bird, cat, deer, dog, frog, horse, ship, truck
]