defaults:
  - invvis
  
_target_: dataset.modules.daliset.WebdalisetDataModule
data_dir: ~/data/invvis/webds/initial
extensions: [img, lbl]

mean:  [0.1833, 0.2464, 0.2912]
std:   [0.2288, 0.2195, 0.2093]