defaults:
  - invvis
  
_target_: dataset.modules.daliset.WebdalisetDataModule
data_dir: ~/data/invvis/webds/initial
extensions: [img, dep, lbl]
mean: [0.1605, 0.2303, 0.2896, 0.8826]
std:  [0.2156, 0.2101, 0.2017, 0.2881]