_target_: torch.optim.lr_scheduler.OneCycleLR
max_lr: ${model.optimizer.lr}
total_steps: ${trainer.max_steps}

pct_start: 0.1
anneal_strategy: cos
cycle_momentum: true
base_momentum: 0.85
max_momentum: 0.95
div_factor: 25.0
final_div_factor: 10000.0
three_phase: false